export const SectionID = {
  BACKGROUND: 'background',
  NEEDS: 'needs',
  PHILOSOPHY: 'philosophy',
  ATTRIBUTES: 'attributes',
  MISSION: 'mission',
  VISION: 'vision',
  PEOS: 'peos',
  PLOS: 'plos',
  DESCRIPTION: 'description',
  BENCHMARKING: 'benchmarking',
  STRUCTURE: 'structure',
  TL_PRINCIPLES: 'tl_principles',
  ASSESSMENT_PRINCIPLES: 'assessment_principles',
  GRADUATE_PROFILE: 'graduate_profile',
  ADMISSION: 'admission',
  DURATION: 'duration',
  REQUIREMENTS: 'requirements',
  CAREER: 'career',
  RESEARCH: 'research',
  STAFF: 'staff',
  FACILITIES: 'facilities',
  RESOURCES: 'resources',
  QA: 'qa',
  ALUMNI: 'alumni',
  FAQ: 'faq',
  ABOUT: 'about'
};